service:
  http:
    externalHost: gitea.do.imim.cloud
  ssh:
    serviceType: NodePort
    port: 22
    nodePort: 30222
    externalHost: d1.do.imim.cloud
    externalPort: 30222

ingressRoute:
  enabled: true
  host: gitea.do.imim.cloud
  tls:
    certResolver: default

config:
#  secretKey: define_your_secret
  disableInstaller: false
  offlineMode: false
  requireSignin: true
  disableRegistration: true
  openidSignin: true
  lfsStartServer: true

  #externalDB:
  #  dbUser: "test"
  #  dbPassword: "testtest"
  #  dbHost: "postgres-postgresql.gitea.svc.cluster.local" # or some external host
  #  dbPort: "5432"
  #  dbDatabase: "gitea"

# valid types: postgres, mysql, mssql, sqllite
dbType: "postgres"
useInPodPostgres: false

persistence:
  enabled: true
  #existingGiteaClaim: gitea-gitea
  #existingPostgresClaim: gitea-postgres
  giteaSize: 10Gi
  #postgresSize: 5Gi
  storageClass: nfs
  accessMode: ReadWriteMany

repoIndexer:
  enabled: true

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  gitea:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1
  postgres:
    requests:
      memory: 100Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 1
  memcached:
    requests:
      memory: 64Mi
      cpu: 50m
